### PR TITLE
Feature - Use taipy-config

### PR DESCRIPTION
**Pull request by khaitruong922**

### CODE REVIEW

**Comment by jrobinAV** [comment]
I pushed some fixes. @khaitruong922 please have a look and merge if you agree.

**Review by jrobinAV — DISMISSED** [review]

**Comment by jrobinAV** [comment]
@joaoandre @khaitruong922 @dinhlongviolin1 
Please have a look at the Rest.py file. I would like to use the global config to set the 3 Flask parameters. Does it make sense for you?

@dinhlongviolin1 I believe that the Rest app is injected in GUI when we run both. please check if this proposal is compatible with GUI.

**Comment by khaitruong922** [comment]
I prefer to have the 3 parameters since they are more specific to Flask and not polluting the global app config namespace.

**Review by dinhlongviolin1 — APPROVED** [review]
Right now on the gui we are not using these parameters that the rest are using to set up the flask server. So it could either be in the global_config or not. I suppose for overall coherent user experience,  you can move it to the global_config.

**Comment by joaoandre-avaiga** [comment]
> I would like to use the global config to set the 3 Flask parameters. Does it make sense for you?

Yes, I think it's fine to move it to the global_config.

**Review by joaoandre-avaiga — APPROVED** [review]

**Pull request merged**
